name: simulation-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - IPython
  - ipywidgets
  - scipy
  - traitlets
  - basemap
  - ipykernel
  - ipyleaflet
  - ipympl
  - ffmpeg
  - jupyter_contrib_nbextensions
